### ISSUE TITLE
 Unable to change hotkey, always goes back to 'h'

### ISSUE THREAD

**Issue by ghost** [manulaiko/ulauncher-openInBrowser#1]
![screenshot from 2018-01-26 18-00-12](https://user-images.githubusercontent.com/8528269/35434731-1ca196a6-02c3-11e8-80ea-de61a1bca60c.png)

Pretty self-explanatory.

I'm on Linux Mint 18.1 Serena.

**Comment by ho3ein-mola** [comment]
same on linux

**Comment by manulaiko** [comment]
I tried looking at it, but couldn't figure out what was wrong since it would be obvious that this is handled by uLauncher itself.

Anyway, this repo is pretty much unmaintained since I am now using KDE plasma and KRunner already does this, so anyone is free to fork the repo and I'll put a link in README.
